---
# tasks file for roles/database
 - name: Run Database
   docker_container:
     name: database
     image: evesquematthieu/devopstp_database:latest
     networks:
       - name: TP3
     env:
       POSTGRES_DB : db
       POSTGRES_USER: usr
       POSTGRES_PASSWORD : pwd 
